### ISSUE TITLE
Saving a draft should give the user a notification

### ISSUE THREAD

**Issue by kels0la** [kels0la/bittoka#187]
Something simple like displaying "Draft Saved!"

**Comment by robbyphillips** [comment]
There's a few ways to go about doing this. 

1. Locally, specific to this component we can set a 'loading' or 'pendingSave' state variable and change the button message while that state variable is true
2. Do the same local state variable but have a different place for the message
3. Implement an application-wide message/notification system.  We might be able to leverage current application-wide modal system for this... or it would take similar form but be something else.  It's a bigger project, but we could use it anywhere else we want to send notifications..

(sidenote: I've already implemented a version of 1. in #199 )

**Comment by robbyphillips** [comment]
closed by #199 
Will likely have to revisit one of the more complete solutions at a later date.
